module_name: Block Links
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - links
  - menu
  - link block
description_short: The block link allows you to add a menu of custom links to your site.
description: description.md
images:
  - image-1.png
license: AFL
